name: http_certificate_pinning
description: Https Certificate pinning for Flutter
version: 1.0.4
author: Diefferson Santos <diefferson.sts@gmail.com>
homepage: https://github.com/diefferson/http_certificate_pinning

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.10
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: diefferson.http_certificate_pinning
        pluginClass: HttpCertificatePinningPlugin
      ios:
        pluginClass: HttpCertificatePinningPlugin
