name: http_certificate_pinning
description: Https Certificate pinning for Flutter. Checks the equality between the known SHA-1 or SHA-256 fingerprint and the SHA-1 or SHA-256 of the target server.
version: 3.0.1
homepage: https://github.com/diefferson/http_certificate_pinning

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  dio: '>=4.0.6 <6.0.0'
  flutter:
    sdk: flutter
  http: ^1.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: diefferson.http_certificate_pinning
        pluginClass: HttpCertificatePinningPlugin
      ios:
        pluginClass: HttpCertificatePinningPlugin
