name: http_certificate_pinning
description: Https Certificate pinning for Flutter
version: 2.0.2
author: Diefferson Santos <diefferson.sts@gmail.com>
homepage: https://github.com/diefferson/http_certificate_pinning

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  dio: ^4.0.0
  flutter:
    sdk: flutter
  http: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: diefferson.http_certificate_pinning
        pluginClass: HttpCertificatePinningPlugin
      ios:
        pluginClass: HttpCertificatePinningPlugin
